project_id = "xjqysurmwoukskgkwjjc"

[functions.ai-edit-image]
verify_jwt = true

[functions.compress-image]
verify_jwt = true

[functions.upload-shared-file]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
